### ISSUE TITLE
We need to discuss, if we want to allow configuration paths of e.g. bsub binary configuration

### ISSUE THREAD

**Issue by dankwart-de** [eilslabs/BatchEuphoria#88]
Our admin just explained me, that a default and standard behaviour for non interactive sessions is, that e.g. bsub is not in the path, when it is called via ssh.

For our PBS cluster we had a SUSE system which was behaving in a non-standard way (as told to me). There, the .bashrc was also loaded in non-interactive sessions.

Our LSF cluster behaves standard conform (as explained) and there we'd either need to add something to the .bashrc or .bash_profile OR we need to call bsub/bjobs etc. with the full path.

For this case, we could introduce:
- A check, if the submission binaries are accessible
- Informational messages, if they could not be found and what to do
- A way to configure the paths of used submission binaries

**Comment by vinjana** [comment]
I think this is not necessary to check, because the error message already shows that something is wrong.

I also thought, that configuring the paths of used submission binaries may be useful, but the binary paths are not the only problem. The submission command requires many additional variables that are loaded from a dedicated startup script on our cluster. We cannot set everything and therefore we'd better not set anything.

In my opinion, it is the responsibility of the cluster admin to provide proper support and information to the users to set up their environment correctly.
